language: haskell
ghc: 
  - 7.6
  - 7.8

notifications:
  email:
    recipients: corentin.dupont@gmail.com

install:
  - cabal install happy-1.19.3
  - cabal install --ghc-options=-DNO_INTERPRET_QUOTES Nomyx-Language/ Nomyx-Library/ Nomyx-Core/ Nomyx-Web/ Nomyx/ --constraint mtl==2.1.* -f -integer-simple

script: Nomyx/tests.sh

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

