language: haskell
ghc: 
  - 7.6
  - 7.8
notifications:
  email:
    recipients: corentin.dupont@gmail.com
install: cabal install --ghc-options=-DNO_INTERPRET_QUOTES Nomyx-Language/ Nomyx-Core/ Nomyx-Web/ Nomyx/
script: Nomyx/tests.sh
sudo: false
