packages:
- location: Nomyx
- location: Nomyx-Core
- location: Nomyx-Language
- location: Nomyx-Library
- location: Nomyx-Web
- location: Nomyx-Api
- location: Nomyx-Auth
- location: Nomyx-Client
- location: Imprevu
- location: Imprevu-Happstack
- location: shortcut
extra-deps:
- DebugTraceHelpers-0.12
- time-recurrence-0.9.2
- web-routes-regular-0.19.0.1
- regular-0.3.4.4
- NoTrace-0.3.0.1
- hint-server-1.4.3
- eprocess-1.7.2
resolver: lts-7.14
