packages:
- location: Nomyx
- location: Nomyx-Core
- location: Nomyx-Language
- location: Nomyx-Library
- location: Nomyx-Web
- location: Nomyx-Api
extra-deps:
- servant-mock-0.4.4.6
- hint-server-1.4.2
- DebugTraceHelpers-0.12
- eprocess-1.7.2
- time-recurrence-0.9.2
- web-routes-regular-0.19.0.1
- regular-0.3.4.4
resolver: lts-5.11
