# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Nomyx API
  description: The API of Nomyx game 
  version: "1.0.0"
# the domain of the service
host: api.nomyx.net
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /players:
    get:
      summary: infos on players
      responses:
        200:
          description: An array of players
          schema:
            type: array
            items:
              $ref: '#/definitions/Player'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Player:
    type: object
    properties:
      name:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
