resolver: lts-5.11
packages:
- '.'
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Api
  extra-dep: true
- location: ../Nomyx-Core
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
extra-deps:
- Nomyx-Language-0.7.6
- Nomyx-Api-0.7.6
- Nomyx-Library-0.7.6
- Nomyx-Core-0.7.6
- DebugTraceHelpers-0.12
- hint-server-1.4.2
- eprocess-1.7.2
- time-recurrence-0.9.2
flags: {}
extra-package-dbs: []
