flags: {}
packages:
- '.'
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../Imprevu
  extra-dep: true
- location: ../shortcut
  extra-dep: true
extra-deps:
- DebugTraceHelpers-0.12
- Nomyx-Language-0.7.6
- happstack-authenticate-2.1.4
- hint-server-1.4.1
- eprocess-1.7.1
- time-recurrence-0.9.2
resolver: lts-5.11
ghc-options: 
    "*": -DNO_INTERPRET_QUOTES
