flags: {}
packages:
- '.'
- ../../Haskell/data-lens-2.10.6
- ../../Haskell/data-lens-template-2.1.8
- ../../Haskell/eprocess
- ../../Haskell/hint-server
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
extra-deps:
- harp-0.4
- DebugTraceHelpers-0.12
- Nomyx-Language-0.7.6
- data-lens-2.10.6
- data-lens-fd-2.0.5
- data-lens-template-2.1.8
- either-unwrap-1.1
- happstack-authenticate-2.1.4
- hint-server-1.4.1
- ixset-1.0.6
- boomerang-1.4.5
- eprocess-1.7.1
- happstack-hsp-7.3.5
- happstack-jmacro-7.0.10
- hsp-0.10.0
- hsx-jmacro-7.3.6
- hsx2hs-0.13.3.2
- ixset-typed-0.3
- pwstore-purehaskell-2.1.4
- syb-with-class-0.6.1.6
- time-recurrence-0.9.2
- web-routes-0.27.9
- web-routes-boomerang-0.28.4
- web-routes-happstack-0.23.9
- web-routes-hsp-0.24.6
- web-routes-th-0.22.3
- reform-0.2.7
- reform-blaze-0.2.4
- reform-happstack-0.2.5
- acid-state-0.12.4
- data-ordlist-0.4.7.0
- jwt-0.6.0
# blaze-html-0.7.1.0
resolver: lts-2.19
#nightly-2015-07-19
ghc-options: -DNO_INTERPRET_QUOTES
