flags: {}
packages:
- '.'
- location: ../Nomyx-Language
  extra-dep: true
extra-deps:
- Nomyx-Language-0.7.6
- DebugTraceHelpers-0.12
- time-recurrence-0.9.2
- data-ordlist-0.4.7.0
resolver: lts-5.11
