resolver: lts-5.11
packages:
- '.'
- location: ../Nomyx-Core
  extra-dep: true
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../Imprevu
  extra-dep: true
- location: ../shortcut
  extra-dep: true
extra-deps:
- servant-mock-0.4.4.7
- DebugTraceHelpers-0.12
- hint-server-1.4.2
- eprocess-1.7.2
- time-recurrence-0.9.2
flags: {}
extra-package-dbs: []
