flags: {}
packages:
- '.'
- location: ../Imprevu
  extra-dep: true
- location: ../shortcut
  extra-dep: true
extra-deps:
- DebugTraceHelpers-0.12
- time-recurrence-0.9.2
- Imprevu-0.7.6
resolver: lts-5.11
