flags: {}
packages:
- '.'
- location: ../Nomyx-Core
  extra-dep: true
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../Nomyx-Auth
  extra-dep: true
- ../../Haskell/hint-server
extra-deps:
- Nomyx-Core-0.7.6
- Nomyx-Language-0.7.6
- Nomyx-Library-0.7.6
- DebugTraceHelpers-0.12
- hint-server-1.4.1
- time-recurrence-0.9.2
- eprocess-1.7.2
- web-routes-regular-0.19.0.1
- regular-0.3.4.4
resolver: lts-5.11
