flags: {}
packages:
- '.'
- location: ../Nomyx-Core
  extra-dep: true
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../Nomyx-Web
  extra-dep: true
- location: ../Nomyx-Api
  extra-dep: true
- location: ../Nomyx-Auth
  extra-dep: true
- location: ../Imprevu
  extra-dep: true
- location: ../Imprevu-Happstack
  extra-dep: true
- location: ../shortcut
  extra-dep: true
extra-deps:
- DebugTraceHelpers-0.12
- time-recurrence-0.9.2
- NoTrace-0.3.0.1
- hint-server-1.4.3
- eprocess-1.7.2
resolver: lts-7.14
